//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BsmBL.ExchangeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ExchangeService.ExchangeInfoServiceSoap")]
    public interface ExchangeInfoServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getEmpFullName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getEmpFullName(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getEmpFullName", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getEmpFullNameAsync(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getEmpNumByUserName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getEmpNumByUserName(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getEmpNumByUserName", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getEmpNumByUserNameAsync(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUserPropertyByUserName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getUserPropertyByUserName(string userName, string propertyName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUserPropertyByUserName", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getUserPropertyByUserNameAsync(string userName, string propertyName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ExchangeInfoServiceSoapChannel : BsmBL.ExchangeService.ExchangeInfoServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExchangeInfoServiceSoapClient : System.ServiceModel.ClientBase<BsmBL.ExchangeService.ExchangeInfoServiceSoap>, BsmBL.ExchangeService.ExchangeInfoServiceSoap {
        
        public ExchangeInfoServiceSoapClient() {
        }
        
        public ExchangeInfoServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExchangeInfoServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExchangeInfoServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExchangeInfoServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getEmpFullName(string userName) {
            return base.Channel.getEmpFullName(userName);
        }
        
        public System.Threading.Tasks.Task<string> getEmpFullNameAsync(string userName) {
            return base.Channel.getEmpFullNameAsync(userName);
        }
        
        public string getEmpNumByUserName(string userName) {
            return base.Channel.getEmpNumByUserName(userName);
        }
        
        public System.Threading.Tasks.Task<string> getEmpNumByUserNameAsync(string userName) {
            return base.Channel.getEmpNumByUserNameAsync(userName);
        }
        
        public string getUserPropertyByUserName(string userName, string propertyName) {
            return base.Channel.getUserPropertyByUserName(userName, propertyName);
        }
        
        public System.Threading.Tasks.Task<string> getUserPropertyByUserNameAsync(string userName, string propertyName) {
            return base.Channel.getUserPropertyByUserNameAsync(userName, propertyName);
        }
    }
}
