//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BsmCommon.UDT
{
    using System;
    using Oracle.DataAccess.Client;
    using Oracle.DataAccess.Types;
    using System.Xml.Serialization;
    using System.Xml.Schema;
    using BsmCommon.Helpers;

    
    public class COLL_BUDGET_EMPLOYEES_MICHSA : INullable, IOracleCustomType, IXmlSerializable {
        
        private bool m_IsNull;
        
        private OBJ_BUDGET_EMPLOYEES_MICHSA[] m_OBJ_BUDGET_EMPLOYEES_MICHSA;
        
        public COLL_BUDGET_EMPLOYEES_MICHSA() {
            // TODO : Add code to initialise the object
        }
        
        public COLL_BUDGET_EMPLOYEES_MICHSA(string str) {
            // TODO : Add code to initialise the object based on the given string 
        }
        
        public virtual bool IsNull {
            get {
                return this.m_IsNull;
            }
        }
        
        public static COLL_BUDGET_EMPLOYEES_MICHSA Null {
            get {
                COLL_BUDGET_EMPLOYEES_MICHSA obj = new COLL_BUDGET_EMPLOYEES_MICHSA();
                obj.m_IsNull = true;
                return obj;
            }
        }

        public void Add(OBJ_BUDGET_EMPLOYEES_MICHSA Object)
        {
            if (Object.IsNull) return;

            int Size;
            if (m_OBJ_BUDGET_EMPLOYEES_MICHSA == null)
            {
                m_OBJ_BUDGET_EMPLOYEES_MICHSA = new OBJ_BUDGET_EMPLOYEES_MICHSA[1];
                m_OBJ_BUDGET_EMPLOYEES_MICHSA[0] = Object;
            }
            else
            {
                Size = m_OBJ_BUDGET_EMPLOYEES_MICHSA.Length;
                m_OBJ_BUDGET_EMPLOYEES_MICHSA = (OBJ_BUDGET_EMPLOYEES_MICHSA[])ArrayHelper.ResizeArray(m_OBJ_BUDGET_EMPLOYEES_MICHSA, Size + 1);
                m_OBJ_BUDGET_EMPLOYEES_MICHSA[Size] = Object;

            }
            this.m_IsNull = false;

        }

        [OracleArrayMappingAttribute()]
        public virtual OBJ_BUDGET_EMPLOYEES_MICHSA[] Value {
            get {
                return this.m_OBJ_BUDGET_EMPLOYEES_MICHSA;
            }
            set {
                this.m_OBJ_BUDGET_EMPLOYEES_MICHSA = value;
            }
        }
        
        public virtual void FromCustomObject(Oracle.DataAccess.Client.OracleConnection con, System.IntPtr pUdt) {
            OracleUdt.SetValue(con, pUdt, 0, this.m_OBJ_BUDGET_EMPLOYEES_MICHSA);
        }
        
        public virtual void ToCustomObject(Oracle.DataAccess.Client.OracleConnection con, System.IntPtr pUdt) {
            this.m_OBJ_BUDGET_EMPLOYEES_MICHSA = ((OBJ_BUDGET_EMPLOYEES_MICHSA[])(OracleUdt.GetValue(con, pUdt, 0)));
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader) {
            // TODO : Read Serialized Xml Data
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer) {
            // TODO : Serialize object to xml data
        }
        
        public virtual XmlSchema GetSchema() {
            // TODO : Implement GetSchema
            return null;
        }
        
        public override string ToString() {
            // TODO : Return a string that represents the current object
            return "";
        }
        
        public static COLL_BUDGET_EMPLOYEES_MICHSA Parse(string str) {
            // TODO : Add code needed to parse the string and get the object represented by the string
            return new COLL_BUDGET_EMPLOYEES_MICHSA();
        }
    }
    
    // Factory to create an object for the above class
    [OracleCustomTypeMappingAttribute("HOUR_BANK.COLL_BUDGET_EMPLOYEES_MICHSA")]
    public class COLL_BUDGET_EMPLOYEES_MICHSAFactory : IOracleCustomTypeFactory, IOracleArrayTypeFactory {
        
        public virtual IOracleCustomType CreateObject() {
            COLL_BUDGET_EMPLOYEES_MICHSA obj = new COLL_BUDGET_EMPLOYEES_MICHSA();
            return obj;
        }
        
        public virtual System.Array CreateArray(int length) {
            OBJ_BUDGET_EMPLOYEES_MICHSA[] collElem = new OBJ_BUDGET_EMPLOYEES_MICHSA[length];
            return collElem;
        }
        
        public virtual System.Array CreateStatusArray(int length) {
            return null;
        }
    }
}
